# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stately
description: The Jekyll theme for government
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
gems:
  - jemoji
permalink: pretty
sass:
  sass_dir: assets/css/
  # Load dependancies
  load_paths:
    - node_modules/
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - Gruntfile.js
  - circle.yml
  - vendor

# Stately settings
nav_logo_file: assets/images/stately-logo.png # path to the logo file for the main nav (supports svg, png, jpg, gif). Delete this line for no logo.
footer_logo_file: assets/images/stately-logo.png # path to the logo file for the footer nav (supports svg, png, jpg, gif). Delete this line for no logo.
github_link: true # Display link to edit page content on GitHub. Delete this line or set to false for no link.
github_pages_branch: master # Branch where gh-pages site is hosted (either master, master/docs, or gh-pages). Delete this line for no GitHub pages branch.

## Info bar settings
# info_bar: true # Bar at the top of all pages. Delete this line or set to false for no info bar display.
# info_bar_text: This is not an offical site of the <a href="//usa.gov" class="text-white text-underline">U.S. Government</a> # Only shows if info_bar == true
